project:                
  type: website          
  output-dir: docs       
  
website:
  title: "Mujeres en la Industria Cinematográfica"            #- hay q cambiarlo
  favicon: "/imagenes/my_favicon_uv.jpeg"     #- 
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "./imagenes/my_favicon.png"           #---
    background: "#FFC0CB"    #- color de la navbar
    foreground: "#FFFFFF"    #- color navigation elements, text and links that appear in the navbar.
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo"
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/danabm18/
      - icon: envelope
        url: "mailto:dabauma@alumni.uv.es"        
  page-footer:
    border: true
    background: "#FFC0CB"         #--
    left: "© 2024 Dana Bauer"   #--
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/danabm18/  
      - icon: envelope
        url: "maito:dabauma@alumni.uv.es"     
    
format:
  html:
    theme: journal           #- https://quarto.org/docs/output-formats/html-themes.html
    mainfont: Lato
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    toc-location: right
    toc-title: "Índice"
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: false
  message: false
  warning: false
  eval: true
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
                 #- https://quarto.org/docs/projects/code-execution.html#freeze
    

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  
